language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  # Setup Git
  - npm run git:setup
  - git remote add upstream "https://adriancarriger:$GH_TOKEN@github.com/adriancarriger/youtube-speed-changer.git"
  - git fetch upstream
  # Bump version
  - npm run patch
  # Push
  - git push -q upstream HEAD:master
  # Build project with new version number
  - npm run build
  # Deploy
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/